    
title: Eren OZDEK
logo: /images/me.jpg
description: I am a developer and data-*, who is always eager to learn new things, acquire new skills and share his knowledge with other people. I have experience in several areas of computer science, although at the moment I am mainly focused on big data, and on artificial intelligence.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
